### ISSUE TITLE
Code not found.

### ISSUE THREAD

**Issue by sumeetssaurav** [zhibinliao89/fracture_attention_guidance#1]
Thank you for the interesting work. I request you to kindly upload the codes as mentioned in the manuscript "CNN Attention Guidance for Improved Orthopedics Radiographic Fracture Classification".

**Comment by qiqiqiqiqiiq** [comment]
I request you to kindly upload the codes as mentioned in the manuscript "CNN Attention Guidance for Improved Orthopedics Radiographic Fracture Classification"

**Comment by zhibinliao89** [comment]
My sincere apologies for the delay. Please find the code uploaded
